image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/
ports:
- port: 3000

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/44_config_start_tasks/
tasks:
- init: echo 'init script' # runs during prebuild
  command: echo 'start script'

vscode:
  extensions:
    - eg2.vscode-npm-script@0.3.8:VERVP8BWgmE+aB6pxK1YPA==
    - ms-vsts.team@1.149.2:+I7fhWnHHHFPms/pHGQ/LQ==
    - humao.rest-client@0.22.0:lpuKvZoPinhQd8yJlJAj+A==
    - christian-kohler.npm-intellisense@1.3.0:yQtCdwoyo890Bn9NOEuEDA==
    - christian-kohler.path-intellisense@1.4.2:QnOrf5fk6KiVaQs4cNEP+w==
    - redhat.fabric8-analytics@0.0.13:k9RQ8fqmg2WmkP2sL4ccbA==
    - cosformula.vscode-drone-status@0.0.4:gp7txvVDwF7BOoVU8XjTQw==
